### PR TITLE
V_1 To detect Number plate using CV2

### PR DESCRIPTION
**Pull request by RudrakshSugandhi**

### CODE REVIEW

**Comment by zeshengchen** [comment]
Again, this pull request was merged into main branch without peer reviews and approvals. Why???????

**Comment by zeshengchen** [comment]
@VarshithaY

**Comment by zeshengchen** [comment]
Please follow the process that we discussed in the class. Moreover, here is the grading rubrics for course projects:
"Is good software development practice followed (e.g., pull requests and code peer review)? (10%) "

**Comment by RudrakshSugandhi** [comment]
Professor Reverted the commit for Peer Review

**Comment by zeshengchen** [comment]
I cannot understand why this happened again, after I talked about the process in the last lecture. :-(

**Pull request merged**
