### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by arponitis**
Added a dataset with Yolov5 annotation, files are split in the format (70/20/10)

### CODE REVIEW

**Review by RudrakshSugandhi — APPROVED** [review]

**Review by RudrakshSugandhi — APPROVED** [review]
We have more datasets from UFPR that will be uploaded after your request is merged in the main branch.

**Comment by zeshengchen** [comment]
It is a bad idea to upload the zip file to GitHub repo.

**Review by BADRI-1999 — APPROVED** [review]

**Comment by RudrakshSugandhi** [comment]
If the file size is more than 8 GB should we just upload the link of the dataset @zeshengchen ?

**Comment by zeshengchen** [comment]
> If the file size is more than 8 GB should we just upload the link of the dataset @zeshengchen ?

Yes, please upload the link(s) instead!

**Review by VarshithaY — APPROVED** [review]

**Pull request merged**
